# Generated by Django 4.2.7 on 2023-12-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_blognotes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognotes',
            name='slug',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
