# Generated by Django 4.2.7 on 2023-12-23 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_versionproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='product_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
    ]
