# Generated by Django 4.2.7 on 2023-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_product_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
